### ISSUE TITLE
Why no _stream->flush(); used?

### ISSUE THREAD

**Issue by wltue** [RobTillaart/RS485#15]
I had issues with the slave, It response so fast the Master didn't put the MAX485 in receive mode yet, missing the first byte of the slave sending.
I changed:
"delayMicroseconds((len + 8 + 2) * _microsPerByte); //  + 2 to be sure..."
in
"void RS485::send(uint8_t receiverID, uint8_t msg[], uint8_t len) {}"

to

"_stream->flush();"

Works perfectly on 2 baud rates, master and slave. Verified on a DPO2024B. Why are timers used?
The master is a Arduino Nano ESP32 with a MAX3471CUA+T.
The slave is a Arduino Zero with a MAX3471CUA+T.
Finally a nice layer library for RS-485. Thanks for the lib.

with "delayMicroseconds((len + 8 + 2) * _microsPerByte); //  + 2 to be sure..." (the blue is the _sendPin)
![TEK00001](https://github.com/RobTillaart/RS485/assets/50613084/552f59b4-4fc2-499d-9db1-4ac7c57d1ae7)

with "f_stream->flush();"
![TEK00000](https://github.com/RobTillaart/RS485/assets/50613084/647e66f5-6b10-45b6-80ba-6f0d21809367)

**Comment by RobTillaart** [comment]
Thanks for this issue.

I used delayMicroseconds() to be sure to wait long enough - as throughput can be calculated.
Apparently the latter part (about calculation) is an assumption on my side as I assumes a certain throughput.

I will check the proposed change **flush()** as it looks like a more robust way to handle it.

>  Finally a nice layer library for RS-485. Thanks for the lib.

Thankyou and you're welcome!

**Comment by RobTillaart** [comment]
had a quick look and it looks good. There are 2 more places to patch the code.

It could imply that 
```cpp
  //  baudRate must match Serial baudRate
  //  micros are needed before RS485 stream may be reset
  //  to (default) receiving mode.
  void     setMicrosPerByte(uint32_t baudRate);
  uint32_t getMicrosPerByte();
```
is not needed anymore thereby simplifying the code.

**Comment by wltue** [comment]
Will test Asap.

**Comment by RobTillaart** [comment]
Created a develop branch to prepare version 0.3.0 with your proposal.
Build-CI is running.

**Comment by RobTillaart** [comment]
PR created, build runs.

**Comment by wltue** [comment]
Works perfect!
I saw you removed the timed versions, but it could be "flush" doesn't work on other devices as I tested.
I tested it on 38400 and 57600 baud.
Thank you!

overview
![TEK00002](https://github.com/RobTillaart/RS485/assets/50613084/9d7a0ac5-cd18-4c5b-84ae-63672faffdf4)

zoomed in switching from tx to rx
![TEK00003](https://github.com/RobTillaart/RS485/assets/50613084/29f67370-05b5-48c1-8e23-b48e9b926100)

zoomed in last byte from slave sending, hex
![TEK00004](https://github.com/RobTillaart/RS485/assets/50613084/b5b82d88-64db-48a1-a2b2-b80516f3f882)

zoomed in last byte from slave sending ascii
![TEK00005](https://github.com/RobTillaart/RS485/assets/50613084/bfe06af7-7839-4ef4-bbf2-a27f8569d75b)

**Comment by RobTillaart** [comment]
> Works perfect!

good to hear, 

>  but it could be "flush" doesn't work on other devices 

The build-CI test it on 5 platforms so I expect it will work.   (see .arduino-ci.yml)
    - uno
    # - due
    # - zero
    # - leonardo
    - m4
    - esp32
    - esp8266
    # - mega2560
    - rpipico
    
If flush is not supported, users should report this, and I will search for a new solution (conditional code)

**Comment by RobTillaart** [comment]
NOte: I cannot view the images in detail => errror 

## This private-user-images.githubusercontent.com page can’t be found

with a large URL,

**Comment by RobTillaart** [comment]
I will merge the PR asap.
