### ISSUE TITLE
pinMode in library works on Arduino Zero , not within Arduino Nano ESP32

### ISSUE THREAD

**Issue by wltue** [RobTillaart/RS485#16]
It looks like 
 " pinMode(_sendPin, OUTPUT);"

Is ignored with the Arduino Nano ESP32.
It works on the Arduino Zero.

I move the " pinMode(_sendPin, OUTPUT);"  to setup main code.

just fyi, could be an issue in native libraries.
Thanks.

**Comment by RobTillaart** [comment]
As it is an Nano problem and not a library issue I won't fix this one. 
Please file an issue at the Arduino Nano ESP32 core.
