### ISSUE TITLE
rs485.recieve; Request for status byte, not a boolean.

### ISSUE THREAD

**Issue by wltue** [RobTillaart/RS485#19]
For e.g. checksum errors, your would like to know this. Now the return of the RS485.RECEIVE is a bool. For checking the status of the connection, the option could be returning the 'state' variable.
Thanks.

**Comment by RobTillaart** [comment]
Yes, is possible. 
However the protocol is to get people started. If they want a more elaborate protocol, they can build one on top of RS485.

**Comment by RobTillaart** [comment]
As this proposal will not be implemented I will close the issue.
